import type {WebGLRenderer} from 'three';
/** Optional on-device counters. GPU timing is asynchronous; no gl.finish/readPixels. */
export class RenderProfile {
 private el=document.createElement('pre');private start=performance.now();private frames=0;private cpu=0;private calls=0;private triangles=0;private shadows=0;private next=0;private gpu:number[]=[];
 private gl:WebGL2RenderingContext;private ext:any;private pending:WebGLQuery[]=[];private active:WebGLQuery|null=null;
 constructor(private renderer:WebGLRenderer){this.el.id='render-profile';this.el.style.cssText='position:fixed;left:12px;bottom:12px;z-index:99;padding:12px;background:#000d;color:#fff;font:14px monospace;pointer-events:none;white-space:pre-wrap';document.body.append(this.el);this.gl=renderer.getContext() as WebGL2RenderingContext;this.ext=this.gl.getExtension('EXT_disjoint_timer_query_webgl2');}
 reset(){this.start=performance.now()+1500;this.frames=this.cpu=this.calls=this.triangles=this.shadows=0;this.gpu=[];this.next=0;this.el.textContent='Render-Messung wird vorbereitet …';}
 begin(){const gl=this.gl;if(this.ext){if(gl.getParameter(this.ext.GPU_DISJOINT_EXT)){for(const q of this.pending)gl.deleteQuery(q);this.pending=[];this.gpu=[];}else{while(this.pending.length&&gl.getQueryParameter(this.pending[0],gl.QUERY_RESULT_AVAILABLE)){const q=this.pending.shift()!;this.gpu.push(gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q);}}if(this.pending.length<4){this.active=gl.createQuery();gl.beginQuery(this.ext.TIME_ELAPSED_EXT,this.active!);}}return performance.now();}
 end(begin:number,shadow:boolean,mode:string){if(this.active){this.gl.endQuery(this.ext.TIME_ELAPSED_EXT);this.pending.push(this.active);this.active=null;}const now=performance.now();if(now<this.start){this.gpu=[];return;}this.frames++;this.cpu+=now-begin;this.calls+=this.renderer.info.render.calls;this.triangles+=this.renderer.info.render.triangles;this.shadows+=Number(shadow);if(now<this.next)return;this.next=now+1000;const seconds=(now-this.start)/1000;this.el.textContent=`${mode} · ${this.renderer.domElement.width} × ${this.renderer.domElement.height}\n${(this.frames/seconds).toFixed(1)} FPS · CPU submit ${(this.cpu/this.frames).toFixed(1)} ms\nGPU ${this.gpu.length?(this.gpu.reduce((a,b)=>a+b,0)/this.gpu.length).toFixed(1)+' ms':'nicht verfügbar'}\nDraw calls Ø ${(this.calls/this.frames).toFixed(1)} · Dreiecke Ø ${Math.round(this.triangles/this.frames)}\nSchatten ${(this.shadows/seconds).toFixed(1)} /s · Messdauer ${seconds.toFixed(0)} s`;if(seconds>=25){this.el.dataset.lastSample=this.el.textContent;this.start=now;this.frames=this.cpu=this.calls=this.triangles=this.shadows=0;this.gpu=[];}}
}
