export class Sound {
 enabled=true;ready=false;private context:AudioContext|null=null;private master:GainNode|null=null;private fx:GainNode|null=null;private bed:GainNode|null=null;
 private rollSource:AudioBufferSourceNode|null=null;private rollFilter:BiquadFilterNode|null=null;private pan:StereoPannerNode|null=null;private ambienceSource:AudioBufferSourceNode|null=null;private timer:number|null=null;
 private effects=.65;private atmosphere=.22;private muted=false;
 async unlock(){this.context??=new AudioContext();if(this.context.state==='suspended')await this.context.resume();if(!this.master){const c=this.context;this.master=c.createGain();this.master.connect(c.destination);this.fx=c.createGain();this.bed=c.createGain();this.fx.connect(this.master);this.bed.connect(this.master);this.startAmbience();}this.ready=this.context.state==='running';this.configure(this.effects,this.atmosphere,this.muted);}
 configure(effects:number,ambience:number,muted:boolean){this.effects=effects;this.atmosphere=ambience;this.muted=muted;if(this.master&&this.context){const t=this.context.currentTime;this.master.gain.setTargetAtTime(muted?0:.75,t,.15);this.fx!.gain.setTargetAtTime(effects,t,.1);this.bed!.gain.setTargetAtTime(ambience,t,.2);}}
 private noise(seconds:number){const c=this.context!,buffer=c.createBuffer(1,Math.ceil(c.sampleRate*seconds),c.sampleRate),data=buffer.getChannelData(0);let low=0;for(let i=0;i<data.length;i++){const white=Math.random()*2-1;low=.985*low+.015*white;data[i]=white*.12+low*2;}return buffer;}
 private startAmbience(){
  const c=this.context!,src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=this.noise(13);src.loop=true;filter.type='bandpass';filter.frequency.value=420;filter.Q.value=.6;gain.gain.value=.8;src.connect(filter).connect(gain).connect(this.bed!);src.start();this.ambienceSource=src;
  // Distant, unintelligible room murmur with moving speech-like resonances.
  for(let i=0;i<5;i++){const voice=c.createBufferSource(),band=c.createBiquadFilter(),level=c.createGain(),pan=c.createStereoPanner();voice.buffer=this.noise(7+i);voice.loop=true;band.type='bandpass';band.frequency.value=300+i*210;band.Q.value=3;level.gain.value=.23;pan.pan.value=(i-2)/2;voice.connect(band).connect(level).connect(pan).connect(this.bed!);voice.start();const lfo=c.createOscillator(),depth=c.createGain();lfo.frequency.value=.17+i*.11;depth.gain.value=.17;lfo.connect(depth).connect(level.gain);lfo.start();}
  this.timer=window.setInterval(()=>{if(!this.ready||this.muted||document.hidden)return;this.click(.10+Math.random()*.12,true,900+Math.random()*1800);if(Math.random()>.6)window.setTimeout(()=>this.click(.07,true,1400),95);},1900);
 }
 roll(){if(!this.ready||!this.context)return;this.stop();const c=this.context;this.rollSource=c.createBufferSource();this.rollSource.buffer=this.noise(4);this.rollSource.loop=true;this.rollFilter=c.createBiquadFilter();this.rollFilter.type='bandpass';this.rollFilter.frequency.value=1600;this.rollFilter.Q.value=.65;const gain=c.createGain();gain.gain.value=.8;this.pan=c.createStereoPanner();this.rollSource.connect(this.rollFilter).connect(gain).connect(this.pan).connect(this.fx!);this.rollSource.start();}
 update(angle:number,progress:number){if(this.context&&this.pan){this.pan.pan.setTargetAtTime(Math.sin(angle)*.7,this.context.currentTime,.025);this.rollFilter!.frequency.setTargetAtTime(1800-progress*1250,this.context.currentTime,.1);}}
 impact(strength=1){this.click(.22+strength*.5,false,850+strength*1500);if(strength<.5)window.setTimeout(()=>this.click(strength*.2,false,1100),65);}
 private click(volume:number,ambient:boolean,pitch:number){if(!this.ready||!this.context)return;const c=this.context,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=this.noise(.11);f.type='bandpass';f.frequency.value=pitch;f.Q.value=1.2;g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.10);s.connect(f).connect(g).connect(ambient?this.bed!:this.fx!);s.start();s.stop(c.currentTime+.11);}
 tick(pitch=1200){this.click(.25,false,pitch);}
 stop(){try{this.rollSource?.stop();}catch{}this.rollSource?.disconnect();this.rollSource=null;this.pan=null;this.rollFilter=null;}
}
