import type {Settings} from './settings';
import {ENGRAVING_NAMES,ENGRAVING_FONT_NAMES,ENGRAVING_WEIGHT_NAMES,ENGRAVING_EFFECT_NAMES,ENGRAVING_COLOR_NAMES} from './track-engraving';
/**
 * Einstellungen in aufklappbaren Gruppen (Fernbedienung und TV-Dialog). Alle Gruppen starten
 * eingeklappt – am Handy sieht man zuerst nur die Überschriften und öffnet, was man braucht.
 */
export function settingsForm(){const group=(title:string,body:string,note='')=>`<details class="picture-settings"><summary>${title}</summary><div class="settings-grid">${body}</div>${note}</details>`;return [
 group('🔊 Ton',`${field('effects','Kugel & Aufpraller','%',0,1,.05)}${field('ambience','Hintergrundgeräusch','%',0,1,.05)}
 <label class="switch"><input type="checkbox" data-setting="muted" data-invert> Ton an</label>
 <label class="switch"><input type="checkbox" data-setting="announce"> Croupier-Stimme (französische Ansage)</label>`),
 group('⏱ Tempo',`${field('delay','Normal · Pause vor dem Abwurf','s',3,60,1)}${field('duration','Normal · Dauer der Kugelrunde','s',12,25,1)}${field('durationSpread','Normal · Abweichung ±','s',0,5,.5)}
 ${field('matchDelay','Spielmodus · Pause vor dem Abwurf','s',3,60,1)}${field('matchDuration','Spielmodus · Dauer der Kugelrunde','s',12,25,1)}${field('matchSpread','Spielmodus · Abweichung ±','s',0,5,.5)}`,
 '<p>Normaler Zyklus und Spielmodus haben ein eigenes Tempo.</p>'),
 group('⚪ Kugel & Einlauf',`${field('ballDiameter','Kugeldurchmesser','mm',18,21,1)}${field('ballMass','Trägheit · Gewichtsreferenz','g',5.3,10.5,.1)}${field('ballBounce','Sprungstärke','%',.5,1.4,.05)}
 ${field('pocketRunMin','Einlauf min. Taschen','',3,20,1)}${field('pocketRunMax','Einlauf max. Taschen','',3,20,1)}
 ${field('deflectorResistanceRadial','Rauten radial · Widerstand','%',0,100,5)}${field('deflectorResistanceTangential','Rauten tangential · Widerstand','%',0,100,5)}${field('ballGloss','Kugel · Glanz','%',0,1,.05)}`,
 '<p>Ab dem nächsten Wurf. Einlauf = Taschen, die die Kugel ab dem Taschenkranz noch wandert. Rauten-Widerstand 0 % = verlustfreier Abprall, 100 % = kein Rückprall.</p>'),
 group('🎡 Kessel · Form & Licht',`${field('cameraTilt','Blickwinkel · 0° = von oben','°',0,32,1)}${field('bowlDepth','3D-Tiefe','%',.85,1.45,.05)}
 ${field('numberSlope','Gefälle des Zahlenkranzes','°',8,28,1)}${field('fretHeight','Steghöhe der Taschen · früher 27 mm','mm',11,25,.5)}${field('numberSize','Zahlen auf dem Kessel','%',.85,1.08,.01)}
 ${field('gloss','Glanz & Reflexionen','%',0,1,.05)}${field('lightContrast','Lichtkontrast','%',0,1,.05)}${field('lightPlay','Lichtspiel · wandernde Spiegelung','%',0,1,.05)}
 ${field('metalWarmth','Metall · Silber bis Gold','%',0,1,.05)}${field('fretBrass','Stege der Taschen · Chrom bis Messing','%',0,1,.05)}${field('fretGloss','Stege der Taschen · matt bis Glanz','%',0,1,.05)}${field('diamondBrass','Rauten · Chrom bis Messing','%',0,1,.05)}${field('diamondGloss','Rauten · matt bis Glanz','%',0,1,.05)}${field('pocketRichness','Taschen · Farbstärke','%',0,1,.05)}
 <label class="switch"><input type="checkbox" data-setting="pocketGlow"> Gewinnfach leuchtet auf</label>
 <label class="switch"><input type="checkbox" data-setting="goldNumbers"> Zahlen in Gold</label>`,
 '<p data-design-note>Form und Zahlen ändern sich nach einem laufenden Wurf. Blickwinkel, Licht und Texte reagieren sofort.</p>'),
 group('🪵 Holz',`${choice('woodOuter','Holzart · Außenrand',WOODS)}${choice('woodTrack','Holzart · Kugellaufbahn',WOODS)}${choice('woodInner','Holzart · Innenkessel',WOODS)}
 ${field('woodWarmth','Holz · dunkel bis warm','%',0,1,.05)}${field('grainTrack','Kugellaufbahn · Maserung','%',0,1,.05)}${field('grainInner','Innenkessel · Maserung','%',0,1,.05)}
 ${field('outerTone','Außenrand · dunkel bis hell','%',.15,1.4,.05)}${field('trackTone','Kugellaufbahn · dunkel bis hell','%',.15,1.4,.05)}${field('innerTone','Innenkessel · dunkel bis hell','%',.15,1.4,.05)}
 ${field('outerGloss','Außenrand · matt bis glänzend','%',0,1,.05)}${field('innerGloss','Innenkessel · matt bis glänzend','%',0,1,.05)}`),
 group('🪙 Gravur in der Kugellaufbahn (oben)',`${choice('trackEngraving','Gravur „City Cafe“',ENGRAVING_NAMES)}<label class="setting-field" style="grid-column:1/-1"><span>Text der Gravur (leer = „CITY CAFE“ des Entwurfs)</span><input type="text" maxlength="48" data-setting="trackEngraveText" aria-label="Text der Gravur" placeholder="leer = City Cafe"></label>
 ${choice('trackEngraveFont','Schriftart',ENGRAVING_FONT_NAMES)}${choice('trackEngraveWeight','Strichstärke',ENGRAVING_WEIGHT_NAMES)}
 ${field('trackEngraveSize','Schriftgröße','%',.6,1.4,.01)}${field('trackEngraveSpacing','Buchstabenabstand','%',.6,1.6,.05)}
 ${choice('trackEngraveEffect','Effekt',ENGRAVING_EFFECT_NAMES)}${choice('trackEngraveColor','Farbe',ENGRAVING_COLOR_NAMES)}
 ${field('trackEngraveDepth','Tiefe · Kontrast der Gravur','%',.4,1.6,.05)}${field('trackEngraveY','Lage · innen ↔ außen','%',-1,1,.05)}`,'<p>Nur Zierde oben auf der Laufbahn zwischen den beiden oberen Rauten, die Kugel spürt nichts davon.</p>'),
 group('🎭 Vorlagen für die Werbetafel',`<label class="setting-field" style="grid-column:1/-1"><span>Vorlage laden (füllt Texte, Farben, Effekte vorne und hinten)</span><select data-preset aria-label="Vorlage für die Werbetafel"><option value="">— Vorlage wählen —</option>${PRESETS.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('')}</select></label>`,'<p>Danach lassen sich alle Texte und Stile darunter weiter einzeln anpassen.</p>'),
 group('✨ Innenkessel · Vorderseite (Schrift)',`<label class="setting-field"><span>Text vorne · 1. Zeile (außen)</span><input type="text" maxlength="48" data-setting="frontText" aria-label="Text vorne im Kessel" placeholder="leer = kein Text"></label>
 <label class="setting-field"><span>Text vorne · 2. Zeile (darüber, Richtung Mitte)</span><input type="text" maxlength="48" data-setting="frontText2" aria-label="Zweite Textzeile vorne" placeholder="leer = keine zweite Zeile"></label>
 <b class="setting-sub">Stil der 1. Zeile</b>${choice('textFont','Schriftart',['Georgia (klassisch)','Playfair Display (elegant)','Cinzel (römische Kapitalen)','Cormorant Garamond (fein)','Bodoni Moda (Casino)','Great Vibes (Schreibschrift)','Limelight (Art déco)','Italiana (schlank, edel)','Abril Fatface (fett, plakativ)','Cinzel Decorative (verziert)'])}${field('textWeight','Strichstärke · dünn bis fett','',400,900,100)}${field('textSize','Schriftgröße','%',.6,1.8,.01)}${field('textSpacing','Buchstabenabstand','%',.75,1.3,.05)}
 ${choice('textEffect','Effekt',['Gold (klassisch)','Geprägt (erhaben)','Eingraviert','Glanzgold (Metall)','Leuchtend','Elfenbein','Silber','Kupfer','Bordeaux (Rot)','Weiß leuchtend'])}${field('textOutline','Kontur (dunkle Kante)','%',0,1,.05)}${choice('textColor','Farbe',['Wie der Effekt','Weiß','Rot','Grün','Blau','Orange','Violett'])}
 <b class="setting-sub">Stil der 2. Zeile</b>${choice('text2Font','Schriftart',['Georgia (klassisch)','Playfair Display (elegant)','Cinzel (römische Kapitalen)','Cormorant Garamond (fein)','Bodoni Moda (Casino)','Great Vibes (Schreibschrift)','Limelight (Art déco)','Italiana (schlank, edel)','Abril Fatface (fett, plakativ)','Cinzel Decorative (verziert)'])}${field('text2Weight','Strichstärke · dünn bis fett','',400,900,100)}${field('text2Size','Schriftgröße','%',.6,1.8,.01)}${field('text2Spacing','Buchstabenabstand','%',.75,1.3,.05)}
 ${choice('text2Effect','Effekt',['Gold (klassisch)','Geprägt (erhaben)','Eingraviert','Glanzgold (Metall)','Leuchtend','Elfenbein','Silber','Kupfer','Bordeaux (Rot)','Weiß leuchtend'])}${field('text2Outline','Kontur (dunkle Kante)','%',0,1,.05)}${choice('text2Color','Farbe',['Wie der Effekt','Weiß','Rot','Grün','Blau','Orange','Violett'])}`),
 group('🪧 Innenkessel · Rückseite (Werbetafel)',`<label class="setting-field"><span>Text hinten · 1. Zeile (außen)</span><input type="text" maxlength="48" data-setting="backText" aria-label="Text hinten im Kessel" placeholder="leer = kein Text"></label>
 <label class="setting-field"><span>Text hinten · 2. Zeile (darunter, Richtung Mitte)</span><input type="text" maxlength="48" data-setting="backText2" aria-label="Zweite Textzeile hinten" placeholder="leer = keine zweite Zeile"></label>
 <b class="setting-sub">Stil der 1. Zeile</b>${choice('backFont','Schriftart',['Georgia (klassisch)','Playfair Display (elegant)','Cinzel (römische Kapitalen)','Cormorant Garamond (fein)','Bodoni Moda (Casino)','Great Vibes (Schreibschrift)','Limelight (Art déco)','Italiana (schlank, edel)','Abril Fatface (fett, plakativ)','Cinzel Decorative (verziert)'])}${field('backWeight','Strichstärke · dünn bis fett','',400,900,100)}${field('backSize','Schriftgröße','%',.6,1.8,.01)}${field('backSpacing','Buchstabenabstand','%',.75,1.3,.05)}
 ${choice('backEffect','Effekt',['Gold (klassisch)','Geprägt (erhaben)','Eingraviert','Glanzgold (Metall)','Leuchtend','Elfenbein','Silber','Kupfer','Bordeaux (Rot)','Weiß leuchtend'])}${field('backOutline','Kontur (dunkle Kante)','%',0,1,.05)}${choice('backColor','Farbe',['Wie der Effekt','Weiß','Rot','Grün','Blau','Orange','Violett'])}
 <b class="setting-sub">Stil der 2. Zeile</b>${choice('back2Font','Schriftart',['Georgia (klassisch)','Playfair Display (elegant)','Cinzel (römische Kapitalen)','Cormorant Garamond (fein)','Bodoni Moda (Casino)','Great Vibes (Schreibschrift)','Limelight (Art déco)','Italiana (schlank, edel)','Abril Fatface (fett, plakativ)','Cinzel Decorative (verziert)'])}${field('back2Weight','Strichstärke · dünn bis fett','',400,900,100)}${field('back2Size','Schriftgröße','%',.6,1.8,.01)}${field('back2Spacing','Buchstabenabstand','%',.75,1.3,.05)}
 ${choice('back2Effect','Effekt',['Gold (klassisch)','Geprägt (erhaben)','Eingraviert','Glanzgold (Metall)','Leuchtend','Elfenbein','Silber','Kupfer','Bordeaux (Rot)','Weiß leuchtend'])}${field('back2Outline','Kontur (dunkle Kante)','%',0,1,.05)}${choice('back2Color','Farbe',['Wie der Effekt','Weiß','Rot','Grün','Blau','Orange','Violett'])}`),
 group('✨ Mittelkreuz & Emblem',` <label class="switch"><input type="checkbox" data-setting="emblem"> Emblem „City Cafe · Fischl“ in der Mitte (nimmt Platz für Textzeilen weg)</label>
 ${choice('crossStyle','Mittelkreuz · Design',['Klassisch','Stern (8 Arme)','Krone','Schlicht (Kappe)','City Cafe (Medaillon)'])}${field('brass','Mittelkreuz · Chrom bis Messing','%',0,1,.05)}`),
 group('📺 TV-Bild & Darstellung',`${field('brightness','Helligkeit','',.65,1.4,.05)}${field('zoom','Kesselgröße · 100 % = volle Höhe','%',.75,1.15,.01)}${field('wheelX','Kessel verschieben · links ↔ rechts','%',-.2,.2,.01)}${field('wheelY','Kessel verschieben · hoch ↕ runter','%',-.15,.15,.01)}${field('panelWidth','Tafel · Breite (Spielmodus)','%',.7,1.3,.05)}${field('panelHeight','Tafel · Höhe (Spielmodus)','%',.6,1.1,.05)}${field('textScale','TV-Texte vergrößern','%',.85,1.3,.05)}${field('feltBackground','Filz-Hintergrund','%',0,1,.05)}
 <label class="switch"><input type="checkbox" data-setting="economy"> Sparsame Darstellung (TV-Box)</label>${field('renderScale','3D-Auflösung im Sparmodus','%',.5,1,.05)}${field('supersample','Kantenglättung · 100 % aus, 150–200 % glatte Ränder (ohne Sparmodus)','%',1,2,.05)}
 <label class="switch"><input type="checkbox" data-setting="correction"> TV-Blickwinkel korrigieren</label>
 ${field('diagonal','Bildschirm','Zoll',24,120,1,'number')}${field('bottomHeight','Unterkante','m',0,4,.05,'number')}${field('distance','Abstand','m',1,10,.1,'number')}${field('eyeHeight','Augenhöhe','m',.5,2.2,.05,'number')}`,
 '<p>Voreinstellung: 55 Zoll · Unterkante 2 m · Abstand 3,5 m · Augenhöhe 1,2 m.</p>'),
 '<button type="button" data-design-reset>Design zurücksetzen</button>'].join('\n');}
const WOODS=['Mahagoni','Nussbaum','Kirsche','Ebenholz','Ahorn'];
type Preset={name:string;front:[string,string];back:[string,string];color:number;effect:number;font:number};
const PRESETS:Preset[]=[
 {name:'Standard · City-Cafe',front:['DEMNÄCHST IM CITY-CAFE: HALLOWEEN PARTY',''],back:['CITY-CAFE KLAGENFURT',''],color:0,effect:0,font:0},
 {name:'Halloween',front:['HALLOWEEN PARTY','DEMNÄCHST IM CITY-CAFE'],back:['HALLOWEEN PARTY 31-10','AB 18:00 UHR'],color:5,effect:4,font:8},
 {name:'Live-Musik',front:['LIVE-MUSIK','HEUTE ABEND IM CITY-CAFE'],back:['LIVE-MUSIK','AB 20:00 UHR'],color:0,effect:3,font:1},
 {name:'Roulette-Abend',front:['ROULETTE-ABEND','LIVE IM CITY-CAFE'],back:['ROULETTE LIVE','JEDEN FREITAG'],color:2,effect:3,font:6},
 {name:'Silvester',front:['SILVESTER PARTY','DAS NEUE JAHR BEGINNT HIER'],back:['SILVESTER 31-12','AB 20:00 UHR'],color:1,effect:9,font:9},
 {name:'Geschlossene Gesellschaft',front:['GESCHLOSSENE GESELLSCHAFT',''],back:['WIR SIND BALD WIEDER FÜR EUCH DA',''],color:0,effect:6,font:7},
];
/** Auswahl einer Vorlage → Einstellungen (Texte, Farben, Effekte, Schrift) für beide Seiten und Zeilen. */
export function presetPatch(event:Event):Partial<Settings>|null{const el=event.target as HTMLSelectElement;if(!el.matches?.('[data-preset]')||el.value==='')return null;const p=PRESETS[Number(el.value)];el.value='';if(!p)return null;
 return {frontText:p.front[0],frontText2:p.front[1],backText:p.back[0],backText2:p.back[1],textColor:p.color,text2Color:p.color,backColor:p.color,back2Color:p.color,textEffect:p.effect,text2Effect:p.effect,backEffect:p.effect,back2Effect:p.effect,textFont:p.font,text2Font:p.font,backFont:p.font,back2Font:p.font} as Partial<Settings>;}
function choice(key:string,label:string,options:string[]){return `<label class="setting-field"><span>${label}</span><select data-setting="${key}" aria-label="${label}">${options.map((o,i)=>`<option value="${i}">${o}</option>`).join('')}</select></label>`;}
function field(key:string,label:string,unit:string,min:number,max:number,step:number,type='range'){return `<label class="setting-field"><span>${label}<output data-value="${key}"></output></span><input type="${type}" min="${min}" max="${max}" step="${step}" data-setting="${key}" data-unit="${unit}" aria-label="${label}"></label>`;}
export function fillSettings(root:HTMLElement,settings:Settings){root.querySelectorAll<HTMLInputElement>('[data-setting]').forEach(input=>{const key=input.dataset.setting as keyof Settings,value=settings[key];if(document.activeElement!==input){if(input.type==='checkbox')input.checked=Boolean(value)!==input.hasAttribute('data-invert');else input.value=String(value);}const output=root.querySelector<HTMLOutputElement>(`[data-value="${key}"]`);if(output){const numeric=Number(value);output.textContent=input.dataset.unit==='%'?`${Math.round(numeric*100)} %`:`${numeric.toLocaleString('de-DE',{maximumFractionDigits:2})} ${input.dataset.unit}`;}});}
export function settingsPatch(event:Event){const input=event.target as HTMLInputElement;if(!input.matches('[data-setting]'))return null;if(input.type!=='checkbox'&&input.type!=='text'&&(!input.validity.valid||input.value===''))return null;return {[input.dataset.setting!]:input.type==='checkbox'?input.checked!==input.hasAttribute('data-invert'):input.type==='text'?input.value:Number(input.value)} as Partial<Settings>;}
export const roundButtons=()=>[30,10,12,50,100,200,null].map(n=>`<button data-rounds="${n??'infinite'}" class="round-preset">${n??'∞'}<span>${n===null?'unendlich':n===30?'Standard':'Runden'}</span></button>`).join('');
