import {Relay} from './relay';import {DEFAULT_DESIGN} from './wheel-shape';import {color} from './game';import {DEFAULT_SETTINGS,applySettings,type State,type Command} from './settings';import {settingsForm,fillSettings,settingsPatch,roundButtons} from './controls';
export function startRemote(){
 const params=new URLSearchParams(location.search),room=/^[a-zA-Z0-9_-]{1,64}$/.test(params.get('raum')||'')?params.get('raum')!:'city-cafe';document.body.className='remote-page';
 document.querySelector('#app')!.innerHTML=`<main class="remote-shell"><header class="remote-heading"><div><span class="eyebrow">CITY CAFE · CROUPIER</span><h1>Roulette</h1></div><span class="remote-link-state" id="link-state">Verbinden …</span></header><p class="remote-room" id="remote-room"></p>
 <section class="remote-live"><div><span>Nächster Abwurf</span><strong id="remote-count">—</strong></div><div><span>Runden übrig</span><strong id="remote-remaining">—</strong></div><div><span>Letzte Zahl</span><strong id="remote-last">—</strong></div><p id="remote-message">Warte auf den TV …</p></section>
 <section><div class="section-label">ZYKLUS STARTEN</div><div class="preset-grid" id="presets">${roundButtons()}</div><p class="helper">Während einer laufenden Kugelrunde wird der neue Zyklus für danach vorgemerkt.</p></section>
 <div class="remote-actions"><button data-action="pause" id="remote-pause">Ⅱ Pausieren</button><button data-action="now">↗ Jetzt drehen</button><button data-action="stop" class="stop-button">■ Stoppen</button></div><p id="command-feedback" role="status"></p>
 <section class="remote-settings"><div class="section-label">EINSTELLUNGEN</div>${settingsForm()}<p class="audio-hint" id="audio-hint">Ton muss einmal direkt am TV aktiviert werden.</p></section><section><div class="section-label">LETZTE 10 ZAHLEN</div><div id="remote-history" class="remote-history"></div></section>
 <footer class="remote-footer"><a id="open-tv" target="_blank" rel="noopener">TV-Anzeige öffnen ↗</a><span>Ein Screen · eine Steuerung</span></footer></main>`;
 const $=<T extends HTMLElement>(id:string)=>document.getElementById(id)! as T;const relay=new Relay('remote');let state:State|null=null,lastReceived=0,pendingId:string|null=null,debounce:number|null=null,pendingPatch={};
 $('remote-room').textContent=`Screen: ${room}`;$<HTMLAnchorElement>('open-tv').href=`./index.html?raum=${encodeURIComponent(room)}`;
 fillSettings($('app'),DEFAULT_SETTINGS);
 function isLive(){return !!state&&Date.now()-lastReceived<6500&&relay.connected;}
 function render(){const live=isLive();$('link-state').textContent=live?'● TV verbunden':'○ Warte auf TV';$('link-state').classList.toggle('online',live);document.querySelectorAll<HTMLButtonElement|HTMLInputElement>('[data-action],[data-rounds],[data-setting],[data-design-reset]').forEach(el=>el.disabled=!live);if(!state)return;
  document.querySelector<HTMLElement>('[data-design-note]')!.textContent=state.designPending?'Neue Kesselform vorgemerkt · wird nach dem Wurf übernommen.':'Form und Zahlen ändern sich nach einem laufenden Wurf. Blickwinkel, Licht und Texte reagieren sofort.';
  $('remote-count').textContent=state.phase==='countdown'?`${state.seconds}s`:state.phase==='spinning'?'Läuft':state.phase==='complete'?'Fertig':'Pause';$('remote-remaining').textContent=state.remaining===null?'∞':String(state.remaining);const last=state.history[0];$('remote-last').textContent=last===undefined?'—':String(last);$('remote-last').className=last===undefined?'':color(last);$('remote-message').textContent=state.message;$('remote-pause').textContent=state.running?'Ⅱ Pausieren':'▶ Fortsetzen';$('remote-pause').dataset.action=state.running?'pause':'resume';$('audio-hint').textContent=state.audioReady?'Kugelton und Atmosphäre werden auf dem TV wiedergegeben.':'Ton einmal direkt am TV mit „Ton aktivieren“ freigeben.';
  document.querySelectorAll<HTMLElement>('[data-rounds]').forEach(el=>el.classList.toggle('selected',(el.dataset.rounds==='infinite'?null:Number(el.dataset.rounds))===state!.total));fillSettings($('app'),state.settings);$('remote-history').innerHTML=state.history.map(n=>`<span class="history-number ${color(n)}">${n}</span>`).join('');
  if(pendingId&&state.lastCommand===pendingId){$('command-feedback').textContent='✓ Am TV übernommen';pendingId=null;}
 }
 async function send(command:Command){if(!isLive()||!state){$('command-feedback').textContent='Der TV ist gerade nicht erreichbar.';return;}$('command-feedback').textContent='Wird gesendet …';pendingId=await relay.send({session:state.session,command});if(!pendingId)$('command-feedback').textContent='Nicht gesendet. Bitte Verbindung prüfen.';}
 document.querySelectorAll<HTMLButtonElement>('[data-rounds]').forEach(b=>b.onclick=()=>void send({action:'start',rounds:b.dataset.rounds==='infinite'?null:Number(b.dataset.rounds)}));
 document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>void send({action:b.dataset.action} as Command));
 document.querySelector<HTMLButtonElement>('[data-design-reset]')!.onclick=()=>{if(debounce!==null)clearTimeout(debounce);pendingPatch={};void send({action:'settings',patch:DEFAULT_DESIGN});};
 $('app').addEventListener('input',event=>{const patch=settingsPatch(event);if(!patch)return;pendingPatch={...pendingPatch,...patch};if(state){state.settings=applySettings(state.settings,patch);fillSettings($('app'),state.settings);}if(debounce!==null)clearTimeout(debounce);debounce=window.setTimeout(()=>{void send({action:'settings',patch:pendingPatch});pendingPatch={};},250);});
 relay.onMessage=body=>{if(!body||typeof body!=='object')return;const v=body as State;if(typeof v.session!=='string'||typeof v.phase!=='string'||!v.settings)return;state={...v,history:Array.isArray(v.history)?v.history.filter(n=>Number.isInteger(n)&&n>=0&&n<=36).slice(0,10):[],settings:applySettings(DEFAULT_SETTINGS,v.settings)};lastReceived=Date.now();render();};relay.onConnection=()=>render();void relay.connect(room);window.setInterval(render,1000);render();
}
