import {DEFAULT_TV,type TVSettings} from './tv-projection';
import {DEFAULT_DESIGN,type DesignSettings} from './wheel-shape';
import type {MatchMode,MatchState} from './match';
export interface Settings extends TVSettings,DesignSettings {ballDiameter:number;ballMass:number;ballBounce:number;pocketRunMin:number;pocketRunMax:number;deflectorResistanceRadial:number;deflectorResistanceTangential:number;delay:number;duration:number;durationSpread:number;matchDelay:number;matchDuration:number;matchSpread:number;effects:number;ambience:number;muted:boolean;brightness:number;zoom:number;economy:boolean;renderScale:number;wheelX:number;wheelY:number;cinematic:boolean;announce:boolean;panelWidth:number;panelHeight:number}
export const DEFAULT_SETTINGS:Settings={...DEFAULT_TV,...DEFAULT_DESIGN,ballDiameter:21,ballMass:8.7,ballBounce:1,pocketRunMin:5,pocketRunMax:15,deflectorResistanceRadial:15,deflectorResistanceTangential:15,delay:4,duration:12,durationSpread:3,matchDelay:4,matchDuration:12,matchSpread:3,effects:.65,ambience:.35,muted:false,brightness:.8,zoom:1,economy:false,renderScale:1,wheelX:0,wheelY:0,cinematic:true,announce:true,panelWidth:1,panelHeight:1};
const ranges:Partial<Record<keyof Settings,[number,number]>>={ballDiameter:[18,21],pocketRunMin:[3,20],pocketRunMax:[3,20],deflectorResistanceRadial:[0,100],deflectorResistanceTangential:[0,100],ballMass:[5.3,10.5],ballBounce:[.5,1.4],innerTone:[.15,1.4],outerTone:[.15,1.4],trackTone:[.15,1.4],innerGloss:[0,1],outerGloss:[0,1],grainTrack:[0,1],grainInner:[0,1],woodOuter:[0,4],woodTrack:[0,4],woodInner:[0,4],crossStyle:[0,4],brass:[0,1],fretBrass:[0,1],fretGloss:[0,1],diamondBrass:[0,1],diamondGloss:[0,1],ballGloss:[0,1],lightPlay:[0,1],feltBackground:[0,1],pocketRichness:[0,1],durationSpread:[0,5],matchSpread:[0,5],matchDelay:[3,60],matchDuration:[12,25],bowlDepth:[.85,1.45],numberSlope:[8,28],numberSize:[.85,1.08],cameraTilt:[0,32],woodWarmth:[0,1],gloss:[0,1],metalWarmth:[0,1],lightContrast:[0,1],textScale:[.85,1.3],renderScale:[.5,1],delay:[3,60],duration:[12,25],effects:[0,1],ambience:[0,1],brightness:[.65,1.4],zoom:[.75,1.15],fretHeight:[11,25],textWeight:[400,900],textSpacing:[.75,1.3],textOutline:[0,1],textSize:[.8,1.15],textFont:[0,4],textEffect:[0,5],wheelX:[-.2,.2],wheelY:[-.15,.15],panelWidth:[.7,1.3],panelHeight:[.6,1.1],diagonal:[24,120],bottomHeight:[0,4],eyeHeight:[.5,2.2],distance:[1,10]};
export function applySettings(current:Settings,patch:unknown):Settings{const next={...current};if(!patch||typeof patch!=='object')return next;for(const key of Object.keys(DEFAULT_SETTINGS) as (keyof Settings)[]){const value=(patch as Record<string,unknown>)[key];const range=ranges[key];if(range&&typeof value==='number'&&Number.isFinite(value))(next as unknown as Record<string,unknown>)[key]=Math.max(range[0],Math.min(range[1],value));else if(typeof current[key]==='boolean'&&typeof value==='boolean')(next as unknown as Record<string,unknown>)[key]=value;
  // Freitext (Lauftext vorne im Kessel): höchstens 48 Zeichen, Großbuchstaben, keine Steuerzeichen
  else if(typeof current[key]==='string'&&typeof value==='string')(next as unknown as Record<string,unknown>)[key]=value.replace(/[\u0000-\u001f]/g,'').trim().slice(0,48).toUpperCase();}
 for(const k of ['woodOuter','woodTrack','woodInner','crossStyle','textFont','textEffect'] as const)next[k]=Math.round(next[k]);next.textWeight=Math.round(next.textWeight/100)*100;
 // Einlauf in ganzen Taschen, min ≤ max: der zuletzt verstellte Regler schiebt den anderen mit.
 next.pocketRunMin=Math.round(next.pocketRunMin);next.pocketRunMax=Math.round(next.pocketRunMax);
 if(next.pocketRunMin>next.pocketRunMax){if('pocketRunMax' in (patch as object)&&!('pocketRunMin' in (patch as object)))next.pocketRunMin=next.pocketRunMax;else next.pocketRunMax=next.pocketRunMin;}
 return next;}
export interface State {session:string;phase:string;seconds:number;remaining:number|null;total:number|null;completed:number;history:number[];message:string;throwInfo:string;settings:Settings;audioReady:boolean;lastCommand:string;running:boolean;designPending?:boolean;match?:MatchState|null;lastMatch?:{match:MatchState;start:number;end:number}|null;
 /** Was der TV-Browser meldet (Fehlersuche): Fläche in CSS-Pixeln, Skalierung, Tafel-Schrift. */
 tv?:{w:number;h:number;dpr:number;font:number;fit:number;ua:string}}
export type Command={action:'start';rounds:number|null}|{action:'pause'|'resume'|'stop'|'now'|'hello'}|{action:'settings';patch:Partial<Settings>}|{action:'match';mode:MatchMode;players:number;rounds?:number|null;names?:string[]}|{action:'matchEnd'}|{action:'names';names:string[]};
