import {DEFAULT_TV,type TVSettings} from './tv-projection';
import {DEFAULT_DESIGN,type DesignSettings} from './wheel-shape';
export interface Settings extends TVSettings,DesignSettings {ballDiameter:number;ballMass:number;ballBounce:number;pocketRunMin:number;pocketRunMax:number;deflectorResistanceRadial:number;deflectorResistanceTangential:number;delay:number;duration:number;durationSpread:number;effects:number;ambience:number;muted:boolean;brightness:number;zoom:number;economy:boolean;renderScale:number}
export const DEFAULT_SETTINGS:Settings={...DEFAULT_TV,...DEFAULT_DESIGN,ballDiameter:21,ballMass:8.7,ballBounce:1,pocketRunMin:5,pocketRunMax:15,deflectorResistanceRadial:15,deflectorResistanceTangential:15,delay:8,duration:16,durationSpread:3,effects:.65,ambience:.35,muted:false,brightness:.8,zoom:1,economy:false,renderScale:1};
const ranges:Partial<Record<keyof Settings,[number,number]>>={ballDiameter:[18,21],pocketRunMin:[3,20],pocketRunMax:[3,20],deflectorResistanceRadial:[0,100],deflectorResistanceTangential:[0,100],ballMass:[5.3,10.5],ballBounce:[.5,1.4],innerTone:[.15,1.4],outerTone:[.15,1.4],trackTone:[.15,1.4],innerGloss:[0,1],outerGloss:[0,1],pocketRichness:[0,1],durationSpread:[0,5],bowlDepth:[.85,1.45],numberSlope:[8,28],numberSize:[.85,1.08],cameraTilt:[0,32],woodWarmth:[0,1],gloss:[0,1],metalWarmth:[0,1],lightContrast:[0,1],textScale:[.85,1.3],renderScale:[.5,1],delay:[3,60],duration:[12,25],effects:[0,1],ambience:[0,1],brightness:[.65,1.4],zoom:[.75,1.15],diagonal:[24,120],bottomHeight:[0,4],eyeHeight:[.5,2.2],distance:[1,10]};
export function applySettings(current:Settings,patch:unknown):Settings{const next={...current};if(!patch||typeof patch!=='object')return next;for(const key of Object.keys(DEFAULT_SETTINGS) as (keyof Settings)[]){const value=(patch as Record<string,unknown>)[key];const range=ranges[key];if(range&&typeof value==='number'&&Number.isFinite(value))(next as unknown as Record<string,unknown>)[key]=Math.max(range[0],Math.min(range[1],value));else if(typeof current[key]==='boolean'&&typeof value==='boolean')(next as unknown as Record<string,unknown>)[key]=value;}
 // Einlauf in ganzen Taschen, min ≤ max: der zuletzt verstellte Regler schiebt den anderen mit.
 next.pocketRunMin=Math.round(next.pocketRunMin);next.pocketRunMax=Math.round(next.pocketRunMax);
 if(next.pocketRunMin>next.pocketRunMax){if('pocketRunMax' in (patch as object)&&!('pocketRunMin' in (patch as object)))next.pocketRunMin=next.pocketRunMax;else next.pocketRunMax=next.pocketRunMin;}
 return next;}
export interface State {session:string;phase:string;seconds:number;remaining:number|null;total:number|null;completed:number;history:number[];message:string;throwInfo:string;settings:Settings;audioReady:boolean;lastCommand:string;running:boolean;designPending?:boolean}
export type Command={action:'start';rounds:number|null}|{action:'pause'|'resume'|'stop'|'now'|'hello'}|{action:'settings';patch:Partial<Settings>};
