import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game,BETS,ORDER,RED,color,randomIndex,sample,STEP,TAU,PlaybackClock,coast,rotorAt,BALL_RADIUS,POCKET_RADIUS,POCKET_Y,supportHeight,reversalPlan,sampleReversal,launchPosition,restingOffset,pocketForAngle,type Motion} from '../src/game';
test('Wiedergabezeit bleibt bei 15/30/60/144 FPS gleich',()=>{for(const fps of [15,30,60,144]){const clock=new PlaybackClock();let elapsed=0;for(let i=0;i<=fps*10;i++)elapsed+=clock.tick(i*1000/fps);assert.ok(Math.abs(elapsed-10)<1e-9);}});
test('Verstecken und Einfrieren überspringen keine Animationszeit',()=>{const clock=new PlaybackClock();clock.tick(0);assert.equal(clock.tick(100),.1);assert.equal(clock.tick(101,false),0);assert.equal(clock.tick(20000),0);assert.equal(clock.tick(20100),.1);assert.equal(clock.tick(80000),0);assert.equal(clock.tick(80100),.1);clock.reset();assert.equal(clock.tick(99999),0);});
test('Europäischer Kessel: jede Zahl genau einmal, korrekte Farben',()=>{assert.equal(ORDER.length,37);assert.deepEqual([...ORDER].sort((a,b)=>a-b),Array.from({length:37},(_,i)=>i));assert.equal(RED.size,18);assert.equal(ORDER.filter(n=>color(n)==='black').length,18);assert.equal(color(0),'green');for(let i=1;i<36;i++)assert.notEqual(color(ORDER[i]),color(ORDER[i+1]));});
test('Zufallsquelle verwirft den ungleichmäßigen Restbereich',()=>{const values=[2**32-1,Math.floor(2**32/37)*37,74];assert.equal(randomIndex(()=>values.shift()!),0);assert.equal(values.length,0);for(let n=0;n<37;n++)assert.equal(randomIndex(()=>n),n);});
for(const b of BETS)test(`Auszahlung ${b.label} über alle 37 Zahlen`,()=>{for(let n=0;n<=36;n++){const g=new Game();g.place(b.id,10);const id=g.start()!;const result=g.settle(id,ORDER.indexOf(n))!;const expected=b.numbers.includes(n)?10*b.multiplier:0;assert.equal(result.payout,expected);assert.equal(g.balance,990+expected);}});
test('Null verliert auf allen sechs einfachen Chancen',()=>{for(const id of ['red','black','odd','even','low','high'])assert.ok(!BETS.find(b=>b.id===id)!.numbers.includes(0));});
test('Rundensperre, Budget, Löschung und genau einmal abrechnen',()=>{const g=new Game();assert.equal(g.start(),null);assert.equal(g.place('fake',10),false);assert.equal(g.place('n0',-1),false);assert.equal(g.place('n0',1001),false);g.place('n0',10);const id=g.start()!;assert.equal(g.start(),null);assert.equal(g.place('n1',10),false);g.clear();assert.equal(g.total,10);assert.equal(g.settle(id,-1),null);assert.equal(g.settle(id,37),null);assert.equal(g.settle(id,0)!.payout,360);assert.equal(g.balance,1350);assert.equal(g.settle(id,0),null);assert.equal(g.balance,1350);g.place('red',5);g.clear();assert.equal(g.total,0);g.place('n1',5);const second=g.start()!;assert.equal(g.settle(id,1),null);assert.ok(g.settle(second,1));});
test('Kombinierte Einsätze werden additiv abgerechnet',()=>{const g=new Game();g.place('n1',10);g.place('red',10);g.place('d0',10);assert.equal(g.settle(g.start()!,ORDER.indexOf(1))!.payout,410);assert.equal(g.balance,1380);});
for(let index=0;index<37;index++)test(`Kugel landet im bewegten Fach ${ORDER[index]} bei 15/30/60/144 FPS`,()=>{for(const fps of [15,30,60,144])for(const variant of [0,1,2])for(const direction of [1,-1] as const){const m:Motion={index,variant,direction,startSpeed:direction*.76,duration:15.5+variant*.7,start:1.93,initialBall:-2.31,initialRadius:POCKET_RADIUS,initialY:POCKET_Y};let last=sample(m,0);assert.equal(last.radius,POCKET_RADIUS);assert.equal(last.y,POCKET_Y);for(let frame=1;frame<=Math.ceil(m.duration*fps);frame++){const p=sample(m,frame/fps);assert.ok(Number.isFinite(p.angle));assert.ok(p.radius>=1.70&&p.radius<=2.901);assert.ok(p.y>=POCKET_Y-1e-9);assert.ok(Math.abs(p.radius-last.radius)<.2);last=p;}const final=sample(m,m.duration+100);const delta=Math.atan2(Math.sin(final.angle-final.rotor-index*STEP-restingOffset(variant).angle),Math.cos(final.angle-final.rotor-index*STEP-restingOffset(variant).angle));assert.ok(Math.abs(delta)<1e-10);assert.equal(final.radius,POCKET_RADIUS+restingOffset(variant).radius);assert.equal(final.y,POCKET_Y);assert.ok(final.done);const before=sample(m,m.duration-1e-5);assert.ok(Math.abs(before.angle-final.angle)<.0001);}});
test('Die Hauptumlaufphase läuft entgegen dem Rotor',()=>{const m:Motion={index:12,variant:1,duration:12,start:0,initialBall:0};const a=sample(m,1),b=sample(m,2);assert.ok(b.angle<a.angle);assert.ok(b.rotor>a.rotor);});
test('Rotor behält beim Einrasten exakt seine Geschwindigkeit',()=>{
 for(const speed of [.32,.5,.76,1.1]){const m:Motion={index:4,variant:0,duration:13.2,start:0,initialBall:0,startSpeed:speed};const end=sample(m,m.duration);const before=(rotorAt(m,m.duration)-rotorAt(m,m.duration-.0001))/.0001;const after=coast(end.speed,.0001).angle/.0001;assert.ok(Math.abs(before-after)<1e-6);assert.ok(end.speed/speed>.86);}
});
test('Nachlauf ist zeitbasiert und bremst über mehrere Sekunden sanft',()=>{const one=coast(.7,10);for(const fps of [15,30,60,144]){let speed=.7,angle=0;for(let i=0;i<fps*10;i++){const s=coast(speed,1/fps);speed=s.speed;angle+=s.angle;}assert.ok(Math.abs(angle-one.angle)<1e-9);assert.ok(Math.abs(speed-one.speed)<1e-9);}});
test('Richtungswechsel erfolgt kontinuierlich durch den Stillstand',()=>{for(const direction of [1,-1] as const){const p=reversalPlan(3,-direction*.68,direction);assert.equal(sampleReversal(p,0).speed,-direction*.68);assert.ok(Math.abs(sampleReversal(p,p.duration).speed-direction*.76)<1e-12);assert.equal(sampleReversal(p,0).angle,3);for(let t=.001;t<p.duration;t+=.001){const a=sampleReversal(p,t),b=sampleReversal(p,t-.001);assert.ok(Math.abs(a.angle-b.angle)<.001);}}});
test('Abwurfpunkt folgt allen letzten Gewinnzahlen unabhängig von Null',()=>{for(let index=0;index<37;index++)for(const angle of [-14,-1,0,2.93,16])for(const direction of [1,-1] as const){const initialBall=launchPosition(angle,index);const m:Motion={index:15,variant:0,duration:15.5,start:angle,startSpeed:direction*.76,initialBall,launchDuration:0,direction};const p=sample(m,0);assert.equal(p.angle,angle+index*STEP);assert.equal(p.radius,2.9);const a=sample(m,1),b=sample(m,1.1);assert.ok(direction*(b.rotor-a.rotor)>0);assert.ok(direction*(b.angle-a.angle)<0);}});
test('Kräftige Sprünge, mehrere Rückpraller und durchgehende Position an jedem Kontakt',()=>{
 const m:Motion={index:23,variant:2,duration:14.5,start:.5,initialBall:1};
 let maxLift=0;const impacts=new Set<number>();
 for(let t=.8;t<m.duration;t+=.002){const p=sample(m,t);maxLift=Math.max(maxLift,p.y-supportHeight(p.radius));if(p.impact>=0)impacts.add(p.impact);assert.ok(p.y>=supportHeight(p.radius)-1e-8);}
 assert.ok(maxLift>.4);assert.equal(impacts.size,9);
 for(const u of [.46,.54,.615,.68,.745,.805,.86,.91,.965,1]){const time=.8+u*(m.duration-.8);const a=sample(m,time-1e-7),b=sample(m,time+1e-7);assert.ok(Math.abs(a.y-b.y)<1e-5);assert.ok(Math.abs(a.radius-b.radius)<1e-5);assert.ok(Math.abs(a.angle-b.angle)<1e-5);}
});



